AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to create DynamoDB tables for food orders and food items, and an IAM role for Lambda with necessary permissions.

Resources:
  FoodOrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FoodOrders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: OrderId
          AttributeType: S
      KeySchema:
        - AttributeName: OrderId
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  FoodItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FoodItems
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: FoodItemId
          AttributeType: S
      KeySchema:
        - AttributeName: FoodItemId
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "FoodApp-Role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                Resource:
                  - !GetAtt FoodOrdersTable.Arn
                  - !GetAtt FoodItemsTable.Arn
              - Effect: Allow
                Action:
                  - ec2:*
                Resource: '*'               
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
